### ISSUE TITLE
Translations available

### ISSUE THREAD

**Issue by quozl** [sugarlabs/playgo-activity#4]
`po/` has not been changed for five years, and there are more recent translations available at translate.sugarlabs.org; alternatively this is the wrong repository.

**Comment by yell0wfl4sh** [comment]
isn't there any other way of getting these translations, like using google translate?
IF NOT, can you guide me through for solving this issue?

**Comment by quozl** [comment]
Sure, but I'm hoping our translations manager @leonardcj will also review; is this the correct repository is the activity hosted somewhere else, and is he aware of the situation.

Here's a shell script that I use to download the translations for an activity; it requires the name of the activity as first argument, and is used on Ubuntu Linux while in the activity repository;

```
#!/bin/sh -e
A=$1
if [ ! -e po ]; then
    echo no po
    exit 2
fi

cd po
wget https://translate.sugarlabs.org/projects/$A/
for x in $(grep "/$A/translate/\"" index.html | cut -d/ -f2 | grep -v projects); do
    echo $x
    wget -q https://translate.sugarlabs.org/$x/$A/export/zip && \
        unzip -q -o zip && \
        rm -f zip
done
rm index.html
```

Then I view the translate.sugarlabs.org list of languages for the activity, and sort the table by descending date.  This gives me an idea of what languages are likely to contain changes.

After that I use `emacs` and `magit` to stage or undo individual changes, make a commit, and push.  My commit usually says "translate.sugarlabs.org synchronisation {en,de,es}" where {en,de,es} are the languages that had changes.

I also run the `setup.py` `genpot` target to update the POT file if needed, and run the other `setup.py` targets to check for new regressions in the plurals phrase.

You can use whatever tools you like, but the end result is a commit that brings in the new translations from the translation subproject.

**Comment by leonardcj** [comment]
We never use Google Translate, only human translators.  It appears from https://translate.sugarlabs.org/projects/PlayGo/ that there are additional translated string available from the following languages:  German, Ukrainian, Lithuanian, Swedish, Chinese (Taiwan), Persian (Farsi), Acholi, Guaraní (Paraguay), Albanian, Hindi, Portuguese, Hebrew.  Give me a chance to review the Pootle quality checks on those PO files and then I'll file a pull request.

**Comment by leonardcj** [comment]
@yashagrawal3 please resolve this issue by downloading the PO files with the following links, unzipping them and submitting a pull request to commit them to the /po directory.  I'm a little busy and my Linux box is not behaving at the moment.

https://translate.sugarlabs.org/he/PlayGo/export/zip
https://translate.sugarlabs.org/pt/PlayGo/export/zip
https://translate.sugarlabs.org/hi/PlayGo/export/zip
https://translate.sugarlabs.org/sq/PlayGo/export/zip
https://translate.sugarlabs.org/gug/PlayGo/export/zip
https://translate.sugarlabs.org/ach/PlayGo/export/zip
https://translate.sugarlabs.org/fa/PlayGo/export/zip
https://translate.sugarlabs.org/zh_TW/PlayGo/export/zip
https://translate.sugarlabs.org/sv/PlayGo/export/zip
https://translate.sugarlabs.org/lt/PlayGo/export/zip
https://translate.sugarlabs.org/uk/PlayGo/export/zip
https://translate.sugarlabs.org/de/PlayGo/export/zip

**Comment by yell0wfl4sh** [comment]
Sure! Happy to help :)

**Comment by leonardcj** [comment]
@yashagrawal3 Thanks
